server:
  port: 8080

spring:
  batch:
    job:
      enabled: false
  application:
    name: tmt
    version: 1.0.0
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:file:./data/tmt;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: false
  jpa:
    database: h2
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

springdoc:
  api-docs:
    enabled: true
  version: v0.0.4

tmt-config:
  message:  a message that can be changed live
  clientUrl: http://localhost:8089/
